import {StyleSheet} from 'react-native';
export default styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  nextText: {
    color: '#FFFFFF',
    width: 38,
    height: 19,
    fontWeight: '700',
    fontSize: 16,
    fontStyle: 'normal',
  },
  signupContainer: {
    flexDirection: 'row',
    top: 20,
    left: 20,
    // backgroundColor: 'red',
    width: 73,
    height: 24,
  },
  signupImage: {
    height: 14,
    width: 7,
    marginRight: 5,
    alignSelf: 'center',
  },
  signupText: {
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 19,
    alignSelf: 'center',
    fontFamily: 'FontsFree-Net-AvenirLTStd-Book',
  },
  mainImage: {
    height: 103,
    width: 103,
    alignSelf: 'center',
    top: 107,
    position: 'absolute',
    // left: 136,
  },
  textInputContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 253,
    // left: 16,
  },
  textInput1: {
    width: 343,
    color: '#BDBDBD',
    height: 56,
    // top: 10,
    //  alignSelf: 'center',
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: '#BDBDBD',
    padding: 10,
    fontSize: 16,
    lineHeight: 19,
    marginBottom: 15,
    fontFamily: 'FontsFree-Net-AvenirLTStd-Book',
  },
  textInput2: {
    margin: 10,

    width: 343,
    color: '#BDBDBD',
    height: 56,
    // top: 10,
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: '#BDBDBD',
    padding: 10,
    fontSize: 16,
    lineHeight: 19,
  },
  orLineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    //    width: '78%',
    marginTop: 15,
  },
  orText: {
    width: 67,
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 19.2,
    color: '#333333',
    marginLeft: 10,
    marginRight: 10,
    fontFamily: 'OpenSans-SemiBold',
  },
  fbGoogleContainer: {
    flexDirection: 'row',
    width: '70%',
    justifyContent: 'space-between',
    marginTop: 20,
    alignSelf: 'center',
  },
  fbContainer: {
    backgroundColor: '#e6eaf2',
    height: 54,
    width: 117,
    justifyContent: 'center',
    borderRadius: 5,
  },
  fbImage: {
    width: 36,
    height: 36,
    alignSelf: 'center',
    //justifyContent: 'center',

    //position: 'absolute',
  },
  googleContainer: {
    backgroundColor: '#fbe8e5',
    height: 54,
    width: 117,
    justifyContent: 'center',
    borderRadius: 5,
  },
  googleImageContainer: {
    width: 36,
    height: 36,
    alignSelf: 'center',
    //justifyContent: 'center',

    //position: 'absolute',
  },
  buttonContainer: {
    marginTop: 47,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: 343,
    height: 57,
    borderRadius: 4,
    backgroundColor: '#FF5F5E',
  },
});
