import {StyleSheet} from 'react-native';
export default styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  nextText: {
    color: '#FFFFFF',
    width: 107,
    height: 19,
    fontWeight: '700',
    fontSize: 16,
    fontStyle: 'normal',
  },
  backContainer: {
    flexDirection: 'row',
    top: 20,
    left: 20,
    // backgroundColor: 'red',
    width: 73,
    height: 24,
  },
  backImage: {
    height: 14,
    width: 7,
    marginRight: 5,
    alignSelf: 'center',
  },
  backText: {
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 19,
    alignSelf: 'center',
  },
  imageContainer: {
    top: 82,
    height: 131,
    width: 123,
    //  left: 139,
    alignSelf: 'center',
    // backgroundColor: 'yellow',
  },
  imageLogo: {
    top: 19,
    left: 16,
    height: 91.08,
    width: 91.08,
    //marginRight: 5,
    //alignSelf: 'center',
    position: 'absolute',
  },
  text1Container: {
    top: 100,
    width: 98,
    height: 140,
    //left: 140
    alignSelf: 'center',
  },
  text1Text: {
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 19,
    //alignSelf: 'center',
  },
  text2Container: {
    width: 234,
    height: 70,
    marginTop: 10,
    alignSelf: 'center',
  },
  text2Text: {
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  text3Container: {
    marginTop: 50,
    alignSelf: 'center',
    width: 79,
    height: 29,
  },
  text3Text: {
    fontSize: 24,
    lineHeight: 29,
    fontWeight: '700',
    color: '#FF5F5E',
  },
  text4Container: {
    // top: 100,
    width: 98,

    height: 19,
    //left: 140
    alignSelf: 'center',
  },
  text4Text: {
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 19,
    color: '#000000',
    //alignSelf: 'center',
  },
  buttonContainer: {
    marginTop: 39,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: 343,
    height: 57,
    borderRadius: 4,
    backgroundColor: '#FF5F5E',
  },
  loginContainerText: {
    marginTop: 26,
    alignSelf: 'center',
    fontSize: 16,
    lineHeight: 19,
    color: '#FF5F5E',
    fontWeight: '700',
  },
  bottomText: {
    position: 'absolute',
    width: 328,
    bottom: 10,
    // left: 24,
    height: 18,
    fontSize: 16,
    lineHeight: 19,
    textAlign: 'center',
    color: '#828282',
    alignSelf: 'center',
  },
});
